export const BRAND = {
  name: "Kanatal Outdoor Adventure",
  shortName: "KOA",
  tagline: "Where the mountains meet the sky",
  owner: "Ajay Ramola",
  phones: ["7500069047", "8077097587", "9286002931"],
  address: "Village Saur Kanatal, Near by Winter Line Cafe, Tehri Garhwal, Uttarakhand",
  website: "www.kanataloutdoor.com",
  instagram: "@kanatal_outdoor",
  instagramUrl: "https://instagram.com/kanatal_outdoor",
  email: "kanataloutdoor@gmail.com",
  whatsapp: "917500069047",
  domain: "https://kanataloutdooradventures.com",
  geo: { lat: 30.4083, lng: 78.4032 },
} as const;

export interface ActivityData {
  title: string;
  slug: string;
  description: string;
  difficulty: string;
  duration: string;
  price: string;
  image: string;
  details: string[];
}

export const activities: ActivityData[] = [
  {
    title: "Giant Swing",
    slug: "giant-swing",
    description: "Experience the ultimate rush on our giant swing — a heart-pounding free-fall and pendulum arc that swings you out over the Himalayan valley below. One of the most thrilling activities at Kanatal Outdoor.",
    difficulty: "Extreme",
    duration: "10 min",
    price: "₹800/person",
    image: "/images/giant-swing.jpg",
    details: [
      "Full safety harness and professional instruction provided",
      "Minimum age: 14 years",
      "Weight limit: 110 kg",
      "Experience a 30-metre free-fall before the pendulum swing",
      "Includes all safety gear and certified operator",
    ],
  },
  {
    title: "Sky Roller",
    slug: "sky-roller",
    description: "Roll through the air on a suspended track high above the ground. The Sky Roller combines a zipline with a roller-coaster-style seated glide, giving you a panoramic view of the surrounding peaks.",
    difficulty: "Moderate",
    duration: "15 min",
    price: "₹700/person",
    image: "/images/sky-roller.png",
    details: [
      "Seated roller-style suspension on a steel cable",
      "Minimum age: 10 years",
      "Spectacular views of the valley during the ride",
      "Full safety briefing before the activity",
      "Perfect for first-time adventure seekers",
    ],
  },
  {
    title: "Zip Line",
    slug: "zip-line",
    description: "Soar across the valley on our high-speed zip line. Feel the wind in your face as you glide from one mountain ridge to another, with nothing but the stunning Himalayan landscape beneath you.",
    difficulty: "Moderate",
    duration: "15 min",
    price: "₹600/person",
    image: "/images/zip-line.jpg",
    details: [
      "One-side and return options available",
      "Minimum age: 8 years",
      "Dual cable safety system",
      "Professional guide assists launch and landing",
      "Available as part of multiple package deals",
    ],
  },
  {
    title: "Sky Cycling",
    slug: "sky-cycling",
    description: "Pedal your way across a suspended cable high above the ground. Sky Cycling offers a unique combination of cycling and aerial adventure — a must-try for thrill enthusiasts visiting Kanatal.",
    difficulty: "Challenging",
    duration: "20 min",
    price: "₹600/person",
    image: "/images/sky-cycling.jpg",
    details: [
      "Cycle on a single cable suspended 50 feet above ground",
      "Minimum age: 12 years",
      "One-side option available in some packages",
      "Full body harness and safety tether included",
      "Requires basic balance and moderate fitness",
    ],
  },
  {
    title: "Horizon Bridge",
    slug: "horizon-bridge",
    description: "Walk across a suspended bridge with the horizon stretching endlessly before you. The Horizon Bridge is a thrilling balance challenge with breathtaking views of the Tehri Garhwal landscape.",
    difficulty: "Easy",
    duration: "25 min",
    price: "₹700/person",
    image: "/images/horizon-bridge.jpg",
    details: [
      "Suspended wooden-plank bridge at height",
      "Minimum age: 6 years",
      "No upper age limit — suitable for families",
      "Full safety harness clipped to overhead cable",
      "Group-friendly activity",
    ],
  },
  {
    title: "Sky Walk",
    slug: "sky-walk",
    description: "Take a stroll on a suspended walkway that offers unobstructed 360-degree views of the surrounding mountains. The Sky Walk is perfect for those who want adventure without extreme intensity.",
    difficulty: "Easy",
    duration: "20 min",
    price: "₹500/person",
    image: "/images/sky-walk.jpg",
    details: [
      "Elevated walkway with handrails and safety line",
      "Minimum age: 6 years",
      "Great for families and first-timers",
      "Photo-friendly with incredible valley backdrops",
      "Guided experience with staff supervision",
    ],
  },
  {
    title: "Rope Course Level 1",
    slug: "rope-course-level-1",
    description: "Beginner-level rope obstacle course designed to build confidence and coordination. Navigate through rope bridges, balance beams, and cargo nets at a moderate height.",
    difficulty: "Easy",
    duration: "30 min",
    price: "₹500/person",
    image: "/images/rope-course-1.jpg",
    details: [
      "Low-height obstacles for beginners",
      "Minimum age: 8 years",
      "Includes rope bridges, balance beams, and cargo nets",
      "Full safety gear and helmet provided",
      "Progression path to Levels 2 and 3",
    ],
  },
  {
    title: "Rope Course Level 2",
    slug: "rope-course-level-2",
    description: "Intermediate rope course with higher platforms and more challenging obstacles. The next step up for those who have conquered Level 1 and want more height and difficulty.",
    difficulty: "Moderate",
    duration: "30 min",
    price: "₹600/person",
    image: "/images/rope-course-2.jpg",
    details: [
      "Increased height and obstacle complexity",
      "Minimum age: 10 years",
      "Requires Level 1 completion or equivalent experience",
      "Includes zip-line exit element",
      "Continuous safety line system",
    ],
  },
  {
    title: "Rope Course Level 3",
    slug: "rope-course-level-3",
    description: "The ultimate rope course challenge. Advanced obstacles at significant heights requiring strength, balance, and mental focus. Our most demanding aerial obstacle course.",
    difficulty: "Extreme",
    duration: "40 min",
    price: "₹800/person",
    image: "/images/rope-course-3.jpg",
    details: [
      "Expert-level obstacles at maximum height",
      "Minimum age: 14 years",
      "Requires Levels 1 and 2 completion",
      "Includes vertical climb elements and long crossings",
      "Our most challenging rope course experience",
    ],
  },
  {
    title: "Wall Climbing",
    slug: "wall-climbing",
    description: "Scale our artificial climbing wall built with varying difficulty routes. Test your grip strength, technique, and endurance as you make your way to the top.",
    difficulty: "Moderate",
    duration: "30 min",
    price: "₹500/person",
    image: "/images/wall-climbing.jpeg",
    details: [
      "Multiple route difficulty levels",
      "Minimum age: 8 years",
      "Professional belay system and instructor",
      "All climbing shoes and chalk provided",
      "Top-rope safety system",
    ],
  },
  {
    title: "Tyre Climbing",
    slug: "tyre-climbing",
    description: "Climb through a suspended structure made of heavy-duty tyres. A fun and physical challenge that tests your agility, coordination, and upper body strength.",
    difficulty: "Easy",
    duration: "20 min",
    price: "₹300/person",
    image: "/images/tyre-climbing.jpeg",
    details: [
      "Suspended tyre obstacle structure",
      "Minimum age: 6 years",
      "Great for younger adventurers",
      "Quick and fun activity",
      "Safe landing area with soft ground covering",
    ],
  },
  {
    title: "Net Climbing",
    slug: "net-climbing",
    description: "Ascend a massive cargo net suspended between trees. Net climbing is a favourite among kids and beginners — a fun way to build confidence at height.",
    difficulty: "Easy",
    duration: "20 min",
    price: "₹300/person",
    image: "/images/net-climbing.jpeg",
    details: [
      "Large cargo net climb to platform",
      "Minimum age: 6 years",
      "Safe and supervised throughout",
      "Good introduction to height-based activities",
      "Quick turnaround — multiple climbs possible",
    ],
  },
  {
    title: "Valley Crossing",
    slug: "valley-crossing",
    description: "Cross a deep Himalayan valley using a rope pulley system. This adrenaline-pumping activity combines balance, nerve, and strength as you traverse from one end to the other.",
    difficulty: "Challenging",
    duration: "30 min",
    price: "₹500/person",
    image: "/images/valley-crossing.jpg",
    details: [
      "Rope pulley traverse across an 80-foot valley gap",
      "Minimum age: 12 years",
      "Full safety rigging with backup lines",
      "Professional guide stationed at both ends",
      "One of the most photographed activities",
    ],
  },
  {
    title: "ATV Ride (2.5 km)",
    slug: "atv-ride",
    description: "Take control of an all-terrain vehicle on a dedicated 2.5 km off-road track through the Himalayan foothills. Mud, bumps, and breathtaking scenery — the ultimate off-road experience.",
    difficulty: "Extreme",
    duration: "30 min",
    price: "₹800/ride",
    image: "/images/atv-ride.jpeg",
    details: [
      "2.5 km dedicated ATV track",
      "Minimum age: 16 years (driving)",
      "Helmet and safety gear provided",
      "Single-rider vehicle",
      "Instruction and supervised trial run included",
    ],
  },
  {
    title: "Jeep Safari",
    slug: "jeep-safari",
    description: "Explore the rugged terrain around Kanatal in a 4x4 jeep. Our Jeep Safari takes you through forest trails, village roads, and mountain paths that regular vehicles cannot reach.",
    difficulty: "Easy",
    duration: "2–3 hrs",
    price: "₹2,500 / ₹4,000",
    image: "/images/jeep-safari.jpg",
    details: [
      "Two pricing options available (₹2,500 / ₹4,000)",
      "Minimum age: 4 years",
      "Covers Kaudia Forest and surrounding trails",
      "Wildlife spotting opportunities",
      "Professional driver and guide included",
    ],
  },
  {
    title: "Kaudia Nature Trek",
    slug: "kaudia-nature-trek",
    description: "Explore the lush Kaudia Forest on a guided nature trek. Spot diverse flora, listen to bird calls, and learn about the local ecosystem from experienced naturalist guides.",
    difficulty: "Moderate",
    duration: "4 hrs",
    price: "₹2,500/trek (3–5 persons)",
    image: "/images/kaudia-trek.jpeg",
    details: [
      "Trek priced per group (₹2,500 for 3–5 persons)",
      "Includes water bottles and food",
      "Professional trek guide",
      "Moderate difficulty — suitable for most fitness levels",
      "Bird watching combined with the trek",
    ],
  },
  {
    title: "Surkanda Temple Trek",
    slug: "surkanda-temple-trek",
    description: "Trek to the historic Surkanda Devi Temple perched at 2,757 metres. This spiritual journey combines breathtaking Himalayan views with a visit to one of the region's most revered temples.",
    difficulty: "Moderate",
    duration: "4 hrs",
    price: "₹2,500/trek (3–5 persons)",
    image: "/images/surkanda-temple.jpeg",
    details: [
      "Trek priced per group (₹2,500 for 3–5 persons)",
      "Includes water bottles and food",
      "3 km trek through oak and pine forest",
      "300 metres elevation gain",
      "360-degree Himalayan panorama at the summit",
    ],
  },
  {
    title: "Bird Watching",
    slug: "bird-watching",
    description: "Discover Kanatal's rich avian diversity on an early morning bird-watching walk. Spot Himalayan blue magpies, verditer flycatchers, rosefinches, and many more species in their natural habitat.",
    difficulty: "Easy",
    duration: "2 hrs",
    price: "Included with treks",
    image: "/images/bird-watching.jpeg",
    details: [
      "Conducted alongside Kaudia Nature Trek",
      "Binoculars and bird guide provided",
      "Best at dawn when bird activity peaks",
      "Common sightings: magpie, flycatcher, rosefinch, barbet",
      "Guided by naturalist who knows local species",
    ],
  },
];

export interface PackageData {
  name: string;
  price: string;
  per: string;
  description: string;
  features: string[];
  popular?: boolean;
  highlight?: string;
  tier?: 1 | 2 | 3 | 4;
}

export const packages: PackageData[] = [
  {
    name: "Package 1",
    price: "₹1,500",
    per: "per person",
    description: "Giant Swing, Sky Cycling, and Zip Line (One Side) — a great introduction to the park's top attractions.",
    features: [
      "Giant Swing",
      "Sky Cycling",
      "Zip Line (One Side)",
    ],
    popular: false,
    tier: 2,
  },
  {
    name: "Package 2",
    price: "₹900",
    per: "per person",
    description: "Horizon Bridge and Zip Line (One Side) — a compact and affordable adventure combo.",
    features: [
      "Horizon Bridge",
      "Zip Line (One Side)",
    ],
    popular: false,
    tier: 1,
  },
  {
    name: "Package 3",
    price: "₹2,100",
    per: "per person",
    description: "Our most popular package featuring Giant Swing, Sky Cycling, Zip Line, Horizon Bridge, and Sky Roller.",
    features: [
      "Giant Swing",
      "Sky Cycling",
      "Zip Line (One Side)",
      "Horizon Bridge",
      "Sky Roller",
    ],
    popular: true,
    tier: 3,
  },
  {
    name: "Giant Swing Package",
    price: "₹1,500 / ₹2,100",
    per: "2 or 3 persons",
    description: "Giant Swing for two or three persons at a special group rate.",
    features: [
      "2 Person Giant Swing – ₹1,500",
      "3 Person Giant Swing – ₹2,100",
    ],
    popular: false,
    tier: 2,
  },
  {
    name: "Package 4",
    price: "₹1,800",
    per: "per person",
    description: "Sky Roller, Horizon Bridge, Sky Cycling, Zip Line, and Rope Course Level 2 — a full day of adventure.",
    features: [
      "Sky Roller",
      "Horizon Bridge",
      "Sky Cycling (One Side)",
      "Zip Line",
      "Rope Course Level 2",
    ],
    popular: false,
  },
  {
    name: "Package 5",
    price: "₹1,200",
    per: "per person",
    description: "Rope Course Level 1, Zip Line, Net Climbing, and Tyre Climbing — ideal for beginners and families.",
    features: [
      "Rope Course Level 1",
      "Zip Line",
      "Net Climbing",
      "Tyre Climbing",
    ],
    popular: false,
    tier: 1,
  },
  {
    name: "Package 6",
    price: "₹1,500",
    per: "per person",
    description: "All three levels of the Rope Course — progress from Level 1 through to Level 3 at a discounted bundle price.",
    features: [
      "Rope Course Level 1",
      "Rope Course Level 2",
      "Rope Course Level 3",
    ],
    popular: false,
    tier: 2,
  },
  {
    name: "Package 7",
    price: "₹2,700",
    per: "per person",
    description: "The ultimate adventure package — Giant Swing, Sky Roller, Horizon Bridge, Sky Cycling, Zip Line, Rope Course Level 3, and Wall Climbing.",
    features: [
      "Giant Swing",
      "Sky Roller",
      "Horizon Bridge",
      "Sky Cycling (One Side)",
      "Zip Line",
      "Rope Course Level 3",
      "Wall Climbing",
    ],
    popular: false,
    highlight: "Best Value",
    tier: 3,
  },
  {
    name: "Full Park Access",
    price: "₹3,800",
    per: "per person",
    description: "Unlimited access to all park activities — the complete Kanatal Outdoor Adventure experience. Excludes Jeep Safari, treks, and bird watching.",
    features: [
      "Giant Swing",
      "Sky Roller",
      "Zip Line",
      "Sky Cycling",
      "Horizon Bridge",
      "Sky Walk",
      "Rope Course (All Levels)",
      "Wall Climbing",
      "Tyre Climbing",
      "Net Climbing",
      "Valley Crossing",
      "ATV Ride (2.5 km)",
    ],
    popular: false,
    highlight: "All Activities",
    tier: 4,
  },
];
